Update ManualAlert.yml

diff --git a/.github/workflows/ManualAlert.yml b/.github/workflows/ManualAlert.yml
--- a/.github/workflows/ManualAlert.yml
+++ b/.github/workflows/ManualAlert.yml
@@ -8,10 +8,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository content
-        uses: actions/checkout@v4 # No update needed for this action
+        uses: actions/checkout@v4
 
       - name: Set up Python
-        uses: actions/setup-python@v5 # Updated to the latest version compatible with Node 20
+        uses: actions/setup-python@v5 # Latest version compatible with Node 20
         with:
           python-version: '3.10'
 
@@ -31,6 +31,7 @@ jobs:
       - name: Check if MarketAlert_New.py is running
         id: check-status
         run: |
+          # Check if the status file exists and if it's marked as running
           if [ -f ".script_status" ] && grep -q "running" .script_status; then
             echo "MarketAlert_New.py is currently running. No action needed."
             echo "status=running" >> $GITHUB_ENV
@@ -44,7 +45,11 @@ jobs:
         run: |
           echo "Starting MarketAlert_New.py..."
           echo "running" > .script_status # Update status to running
-          python MarketAlert_New.py || echo "stopped" > .script_status # Update status if it stops
+          python MarketAlert_New.py || { 
+            echo "Error occurred while running MarketAlert_New.py"; 
+            echo "stopped" > .script_status; 
+            exit 2; 
+          }
         env:
           SOME_SECRET: ${{ secrets.SOME_SECRET }}
 
